name: Node CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [6.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Check Node Version
      run: IF ${{ matrix.node-version }} LSS 8 npm i npm@5 -g
    - name: npm install
      run: npm ci --ignore-scripts
    - name: npm test
      run: npm test
      env:
        CI: true
