name: Node CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install && npm run ci:test
      run: |
        npm ci --ignore-scripts
        node --version && npm --version
        npm test
      env:
        CI: true
